require("telescope")
local builtin = require("telescope.builtin")
vim.keymap.set("n", "<space>ff", builtin.git_files, {})
vim.keymap.set("n", "<space>fh", builtin.help_tags, {})
vim.keymap.set("n", "<space>fg", builtin.live_grep, {})
vim.keymap.set("n", "<space>fr", builtin.lsp_references, {})
vim.keymap.set("n", "<space>fb", builtin.buffers, {})
